# Generated by Django 4.2 on 2023-05-12 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(default='Ernakulam', max_length=20)),
                ('city', models.CharField(default='', max_length=60)),
                ('street', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=60)),
                ('c_phone', models.CharField(max_length=12)),
                ('c_mail', models.EmailField(max_length=50)),
                ('c_password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=60)),
                ('d_photo', models.ImageField(null=True, upload_to='dish/')),
                ('d_price', models.FloatField()),
                ('d_discription', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('status', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='restaurants',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=60)),
                ('r_location', models.CharField(max_length=60)),
                ('license_number', models.CharField(max_length=60)),
                ('license_photo', models.ImageField(null=True, upload_to='license/')),
                ('r_photo', models.ImageField(null=True, upload_to='restaurent_photo/')),
                ('r_mobile', models.CharField(max_length=12, unique=True)),
                ('r_mail', models.EmailField(max_length=30)),
                ('LOGIN_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurryfood.login')),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_table', models.IntegerField()),
                ('t_capacity', models.IntegerField()),
                ('status', models.CharField(default='available', max_length=20)),
                ('total', models.IntegerField()),
                ('RESTAURANT', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('RESTAURANT', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.customer')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('order_number', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.datetime(2023, 5, 12, 15, 0, 20, 449378))),
                ('RESTAURANT', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants')),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.address')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.customer')),
                ('payment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.payment')),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=60)),
                ('of_code', models.CharField(max_length=50)),
                ('offer', models.CharField(max_length=50)),
                ('discount_percentage', models.FloatField(default=None)),
                ('from_date', models.DateField(max_length=20, null=True)),
                ('to_date', models.DateField(max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
                ('DISH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurryfood.dishes')),
                ('RESTAURANT', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=2000)),
                ('RESTAURANT', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.customer')),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=50)),
                ('date', models.DateField()),
                ('NOP', models.IntegerField()),
                ('event_type', models.CharField(max_length=60)),
                ('s_request', models.CharField(max_length=500)),
                ('RESTAURANT', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.customer')),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants'),
        ),
        migrations.CreateModel(
            name='dining',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=50)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('NOP', models.IntegerField()),
                ('s_request', models.CharField(max_length=500)),
                ('RESTAURANT', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurryfood.login'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=2000)),
                ('restaurant', models.CharField(max_length=60)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.customer')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=60)),
                ('ct_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurryfood.customer')),
                ('ct_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurryfood.dishes')),
                ('ct_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='baseorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dish', models.CharField(default='', max_length=70)),
                ('discription', models.CharField(default='', max_length=60)),
                ('quantity', models.CharField(default='', max_length=60)),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=60)),
                ('amount', models.FloatField()),
                ('RESTAURANT', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.customer')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.order')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.customer'),
        ),
    ]
