# Generated by Django 4.1.5 on 2023-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurryfood', '0002_address_remove_baseorder_total_remove_cart_ct_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='discription',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(default='', max_length=60),
        ),
    ]
