# Generated by Django 4.1.5 on 2023-04-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurryfood', '0003_order_date_order_discription_order_dish_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
