# Generated by Django 4.1.5 on 2023-04-30 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hurryfood', '0004_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseorder',
            name='RESTAURANT',
        ),
        migrations.RemoveField(
            model_name='baseorder',
            name='customer',
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('RESTAURANT', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.restaurants')),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.address')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.customer')),
                ('payment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hurryfood.payment')),
            ],
        ),
    ]
