from django.urls import path
from . import views 

urlpatterns = [
    path('',views.landing),
    path('login',views.login_,name="login"),
    path('admin',views.admin_home),
    path('register',views.restuarent_register,name='register'),
    path('view_restaurant',views.view_restaurant,name='view_restaurant'),
    path('block_restaurant/<str:id>',views.block,name='block'),
    path('blocked_restaurant',views.view_block,name='blocked_restaurant'),
    path('un_block_restaurant/<str:id>',views.unblock,name='un_block_restaurant'),
    path('edit_restaurant/<str:id>',views.edit_restaurant,name='edit'),
    path('resaurant',views.restuarant_,name='restaurant'),
    path('dishes',views.add_dish,name='dishes'),
    path('view_dish',views.view_dishes,name='view_dish'),
    path('add_offer',views.add_offer,name='add_offer'),
    path('view_offer',views.view_offer,name='view_offer'),
    path('add_table',views.add_table,name='add_table'),
    path('view_table',views.view_table,name='view_table'),
    path('edit_dish/<str:id>',views.edit_dish,name='edit_dish'),
    path('delete_dish/<str:id>',views.delete_dish,name='delete_dish'),
    path('edit_offer/<str:id>',views.edit_offer,name='edit_offer'),
    path('delete_offer/<str:id>',views.delete_offer,name='delete_offer'),
    path('edittable/<str:id>',views.edit_table,name='edittable'),
    path('delete_table/<str:id>',views.delete_table,name='delete_table'),
    path('available/<str:id>',views.available,name='available'),


    path('customer',views.customer_register,name='customer'),
   
    path('view_restuarants',views.view_restuarents,name='view_restuarants'),
    path('viewhome/<str:id>',views.view_home,name='viewhome'),
    path('cview_dish',views.cview_dish,name='cview_dish'), 
    path('cview_offer',views.cview_offers,name='cview_offer'),
    path('cart/<str:id>',views.add_cart,name='cart'),
    path('view_cart',views.view_cart,name='view_cart'),
    path('place_order',views.place_order,name='place_order'),
    path('reservation',views.reservation,name='reservation'),
    path('cartplus/<str:id>',views.cartplus,name='cartplus'),
    
    path('remove/<str:id>',views.cartremove,name='remove'),
    path('complaint',views.complaints,name='complaint'),
    path('view_complaints',views.view_complaints,name='view_complaints'),
    path('view_reservation',views.view_reservation,name='view_reservation'),
    path('view_dining_reservation',views.view_dining_reservation,name='view_dining_reservation'),
    path('view_event_reservation',views.view_event_reservation,name='view_event_reservation'),
    path('feedback',views.feedbacks,name='feedback'),
    path('viewfeed',views.view_feedback,name='viewfeed'),
    path('cancel/<str:id>',views.cancel_booking,name='cancel'),
    path('insertorder',views.insertbase,name='insertorder'),
    path('location',views.location,name='location'),
    path('remove_event<str:id>',views.delete_event,name='remove_event'),
    path('payment',views.payments,name='payment'),
    path('place',views.place,name='place'),
    path('adress',views.addres,name='adress'),
    path('edit_address/<str:id>',views.edit_address,name='edit_address'),
    path('confirm/<sum1>',views.confirm,name='confirm'),
    path('view_payment',views.view_payments,name='view_payment'),
    path('logout_admin',views.logeout_admin,name='logout_admin'),
    path('logout_rest',views.logeout_rest,name='logout_rest'),
    path('logout_cust',views.logeout_customer,name='logout_cust'),
    path('view_order',views.view_order,name='view_order'),
    path('ready/<str:id>',views.ready,name='ready'),
    path('transaction',views.view_transaction,name='transaction'),
    path('cust_vieworder',views.cust_vieworder,name='cust_vieworder'),
    path('password',views.password,name='password'),
    path('order_cancel/<str:id>',views.order_cancel,name='order_cancel'),
    path('approve/<str:id>',views.approved,name='approve'),
    path('reject/<str:id>',views.reject,name='reject'),
    path('pending',views.view_pending,name='pending'),
    path('profile',views.rest_profile,name='profile'),
    path('view_deliverd',views.view_deliverd_order,name='view_deliverd'),
    path('search',views.search_transaction,name='search'),



    
]